services:
  dataloader:
    image: cosmtrek/air:v1.44.0
    command:
      - "--build.cmd"
      - "go build -o /tmp/dataloader ./cmd/dataloader/main.go"
      - "--build.bin"
      - "/tmp/dataloader"
      - "--build.exclude_dir"
      - ".git,api,cmd/api"
    environment:
      DEBUG: true
      MONGO_URI: "mongodb://mongo:mongopassword@mongodb:27017"
      RABBIT_URI: "amqp://rabbit:rabbitpassword@rabbit:5672"
    env_file:
      - .env
    volumes:
      - .:/app
      - air-go-cache:/go/pkg/mod
    working_dir: /app
    depends_on:
      - mongodb
      - rabbit

  api:
    image: cosmtrek/air:v1.44.0
    command:
      - "--build.cmd"
      - "go build -o /tmp/api ./cmd/api/main.go"
      - "--build.bin"
      - "/tmp/api"
      - "--build.exclude_dir"
      - ".git,dataloader,cmd/dataloader"
    environment:
      DEBUG: true
      MONGO_URI: "mongodb://mongo:mongopassword@mongodb:27017"
      RABBIT_URI: "amqp://rabbit:rabbitpassword@rabbit:5672"
    env_file:
      - .env
    volumes:
      - .:/app
      - air-go-cache:/go/pkg/mod
    working_dir: /app
    ports:
      - 4000:4000
    depends_on:
      - mongodb
      - rabbit

  mongodb:
    image: bitnami/mongodb:6.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb
      - MONGODB_ADVERTISED_PORT_NUMBER=27017
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_USER=mongo
      - MONGODB_ROOT_PASSWORD=mongopassword
      - MONGODB_DATABASE=versions
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/bitnami/mongodb

  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbitpassword
    ports:
      - 15672:15672
      - 15671:15671
    volumes:
      - rabbit-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  rabbit-data:
  air-go-cache:
